<a href="https://colab.research.google.com/github/JeffersonEspinalA/Prueba/blob/main/Hito_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
!git clone https://github.com/lmcanavals/acomplex.git

fatal: destination path 'acomplex' already exists and is not an empty directory.


In [77]:
import numpy as np
import heapq as hq
import random
import math
from acomplex.graphstuff import adjlShow

In [78]:
calles = []
with open("Calles.txt") as f:
  for line in f:
    calle = line.split()
    calles.append(*calle)
print(calles)

['Av.1', 'C.2', 'C.3', 'C.4', 'C.5', 'C.6', 'Av.7', 'C.8', 'C.9', 'C.10', 'C.11', 'C.12', 'Calle_14', 'C.15', 'C.16', 'C.17', 'C.18', 'Av.19', 'C.20', 'C.21', 'C.22', 'C.23', 'C.24', 'Av.25', 'C.26', 'C.27', 'Calle_28', 'C.29', 'C.30', 'Av.31', 'C.132', 'C.133', 'C.134', 'C.135', 'C.136', 'Av.137', 'C.138', 'C.139', 'C.140', 'C.141', 'C.142', 'C.143', 'C.521', 'C.522', 'C.523', 'C.524', 'C.525', 'C.526', 'C.527', 'C.528', 'C.529', 'C.530', 'C.531', 'Av.32', 'C.33', 'C.34', 'C.35', 'C.36', 'C.37', 'Av.38', 'Calle_39', 'C.40', 'C.41', 'Calle_42', 'C.43', 'Av.44', 'C.45', 'C.46', 'C.47', 'C.48', 'C.49', 'C.50', 'Av.51', 'Av.53', 'C.54', 'C.55', 'C.56', 'C.57', 'C.58', 'C.59', 'Av.60', 'C.61', 'C.62', 'C.63', 'C.64', 'C.65']


In [79]:
def generarIntersecciones(calles, archivo, nfilas, ncol, datos):
  n = len(calles)
  if n == nfilas + ncol:
    #Asignar numeros a las calles
    num = 0
    dicc_c = {}
    for calle in calles:
      dicc_c[calle] = num
      num += 1
    
    #Inicializamos el mapa que simule las intersecciones con puros -1  
    I = np.zeros([nfilas,ncol], int)
    I = I - 1

    #Actualizamos la matriz, poniendo los nodos de intersecciones
    with open(archivo) as f:
      for line in f:
        nodo, fila, columna, y, x = [elem for elem in line.split()]
        I[dicc_c[fila], dicc_c[columna] - nfilas] = int(nodo)
        datos[int(nodo)] = (float(x), float(y))

  return I

In [80]:
class Perlin:
    def __init__(self):
        self.gradients = []
        self.lowerBound = 0


    def valueAt(self, t,max):
        if(t<self.lowerBound):
            print("ERROR: Input parameter out of bounds!")
            return
        while t >= len(self.gradients)-1+self.lowerBound:
            self.gradients.append(random.uniform(1, max))

        discarded = int(self.lowerBound) # getting number of gradients that have been discarded
        # Compute products between surrounding gradients and distances from them
        d1 = (t-t//1)
        d2 = d1-1
        a1 = self.gradients[(int)(t//1)-discarded]*d1
        a2 = self.gradients[(int)(t//1+1)-discarded]*d2

        amt = self.__ease(d1)

        return self.__lerp(a1,a2,amt)

    def discard(self, amount):
        gradientsToDiscard = int(amount+self.lowerBound%1)
        self.gradients = self.gradients[gradientsToDiscard:]
        self.lowerBound += amount

    def __ease(self, x):
        return 6*x**5-15*x**4+10*x**3


    def __lerp(self, start, stop, amt):
        return amt*(stop-start)+start

In [81]:
import random
import statistics
import matplotlib.pyplot as plt

def updateTraffic(hour):
  noise=Perlin()
  time=[i*0.01 for i in range(1729)]
  if hour>22 or hour<4:
    values=[int(abs(noise.valueAt(i,20)*2)) for i in time]
    return values
  if hour>=4 and hour<10:
    values=[int(abs(noise.valueAt(i,50)*10)) for i in time]
    return values
  if hour>=10 and hour<14:
    values=[int(abs(noise.valueAt(i,35)*8)) for i in time]
    return values
  if hour>=14 and hour<22:
    values=[int(abs(noise.valueAt(i,45)*10)) for i in time]
    return values
 

In [82]:
ahh=updateTraffic(15)
print(max(ahh))
print(ahh)

100
[0, 1, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14, 14, 15, 15, 15, 15, 14, 14, 13, 12, 11, 10, 9, 7, 5, 4, 2, 0, 2, 4, 7, 9, 12, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 49, 52, 55, 58, 60, 63, 65, 67, 69, 72, 73, 75, 77, 78, 80, 81, 82, 83, 83, 84, 84, 84, 84, 84, 83, 83, 82, 81, 80, 79, 77, 75, 73, 71, 69, 67, 64, 62, 59, 56, 53, 49, 46, 43, 39, 35, 32, 28, 24, 20, 16, 12, 8, 4, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 47, 51, 55, 58, 61, 65, 68, 71, 74, 77, 79, 82, 84, 87, 89, 90, 92, 94, 95, 96, 97, 98, 99, 99, 100, 100, 100, 100, 99, 99, 98, 97, 96, 94, 93, 91, 90, 88, 86, 84, 81, 79, 76, 74, 71, 68, 66, 63, 60, 57, 54, 51, 48, 45, 42, 39, 36, 33, 30, 27, 24, 22, 19, 17, 14, 12, 10, 8, 6, 4, 3, 1, 0, 0, 1, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 1, 1, 0, 0, 0, 1, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 7, 7, 7, 7, 7, 6, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1, 0, 0, 0, 1, 2, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 9, 10, 11, 11, 12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 1

In [83]:
datos = {}
I = generarIntersecciones(calles, "Intersecciones con coordenadas.txt", 42, 44, datos)
print(I)
print(datos)

[[   0    1   -1 ...   35   36   37]
 [  38   39   -1 ...   74   75   76]
 [  77   78   79 ...  118  119  120]
 ...
 [1607 1608 1609 ... 1648 1649 1650]
 [1651 1652 1653 ... 1687 1688 1689]
 [1690 1691 1692 ... 1726 1727 1728]]
{0: (-57.976523, -34.885116), 1: (-57.974166, -34.887932), 2: (-57.967053, -34.89187), 3: (-57.966013, -34.892609), 4: (-57.964961, -34.893386), 5: (-57.963899, -34.894156), 6: (-57.962831, -34.894975), 7: (-57.961672, -34.895855), 8: (-57.960551, -34.8967), 9: (-57.959387, -34.897535), 10: (-57.958293, -34.898376), 11: (-57.957182, -34.899199), 12: (-57.954865, -34.900923), 13: (-57.953728, -34.901799), 14: (-57.95256, -34.902535), 15: (-57.951425, -34.90341), 16: (-57.950321, -34.904207), 17: (-57.949226, -34.905021), 18: (-57.947912, -34.905919), 19: (-57.946834, -34.906706), 20: (-57.945938, -34.907454), 21: (-57.945123, -34.908123), 22: (-57.944345, -34.908721), 23: (-57.943578, -34.909192), 24: (-57.942918, -34.909698), 25: (-57.941663, -34.910582), 26: (-

In [84]:
import math
def haversine(lat1, lon1, lat2, lon2):
    rad=math.pi/180
    dlat=lat2-lat1
    dlon=lon2-lon1
    R=6372.795477598
    a=(math.sin(rad*dlat/2))**2 + math.cos(rad*lat1)*math.cos(rad*lat2)*(math.sin(rad*dlon/2))**2
    distancia=2*R*math.asin(math.sqrt(a))
    return distancia

In [85]:
def peso2calculo(trafficValue):
  a=50-trafficValue
  if a>=25:
    peso2=1.3
    return peso2
  else:
    peso2=0.7
    return peso2

In [86]:
def generarListaAdyacencia2(I, datos,hora):
  G = []
  nfilas, ncol = np.shape(I) 
  values=updateTraffic(hora)
  #Agregar las adyacencias de cada nodo
  for i in range(nfilas):
    for j in range(ncol):
      if I[i,j] > -1:
        aux = []
        x1, y1 = datos[I[i,j]]
        #arriba
        if (i > 0) and (I[i-1, j] > -1):
          x2, y2 = datos[I[i-1, j]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i-1, j], peso))
        #izquierda
        if (j > 0) and (I[i, j-1] > -1):
          x2, y2 = datos[I[i, j-1]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i, j-1], peso))
        #derecha (bug)
        if (j < ncol-1) and (I[i, j+1] > -1):
          x2, y2 = datos[I[i, j+1]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i, j+1], peso))
        #abajo (bug)
        if (i < nfilas-1) and (I[i+1, j] > -1):
          x2, y2 = datos[I[i+1, j]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i+1, j], peso))
        G.append(aux)

  #Guardar en un archivo
  cont = 0
  with open("Lista_Adyacencia_Generado2.txt", 'w') as archivo:
    for lista in G:
      for num in lista:
        archivo.write(str(num) + " ")
      archivo.write("\n")

  return G

In [87]:
a = generarListaAdyacencia2(I, datos,9)
print(a)

[[(1, 0.40344964974194214), (38, 0.11916216347451197)], [(0, 0.40344964974194214), (39, 0.1430240997956625)], [(3, 0.16070423868135952), (40, 0.11265717573480842)], [(2, 0.16070423868135952), (4, 0.1633700598900751), (41, 0.11124244482521904)], [(3, 0.1633700598900751), (5, 0.16452435993900139), (42, 0.11762438821230566)], [(4, 0.16452435993900139), (6, 0.16671453624381127), (43, 0.12092064177938132)], [(5, 0.16671453624381127), (7, 0.1806676130252551), (44, 0.14391652476602135)], [(6, 0.1806676130252551), (8, 0.17456922467559954), (45, 0.15692373841420526)], [(7, 0.17456922467559954), (9, 0.180083562798282), (46, 0.16065818923951472)], [(8, 0.180083562798282), (10, 0.17083585573838608), (47, 0.16542740932503608)], [(9, 0.17083585573838608), (11, 0.17260531526433023), (48, 0.1554421375390512)], [(10, 0.17260531526433023), (49, 0.1577335310338247)], [(13, 0.1776102088091278), (51, 0.15466055846479176)], [(12, 0.1776102088091278), (14, 0.17807626481837574), (52, 0.1587985074032013)], [(1

In [88]:
def dijkstra(G, s, e, p):
  n = len(G)
  visited = [False]*n
  path = [-1]*n
  cost = [math.inf]*n

  cost[s] = 0
  pqueue = [(0, s)]
  while pqueue:
    g, u = hq.heappop(pqueue)
    if u == e:
      break
    if not visited[u]:
      visited[u] = True
      for v, w in G[u]:
        if not visited[v]:
          f = g + w
          if f < cost[v]:
            if (v == e) and (f <= p):
              pass
            else:
              cost[v] = f
              path[v] = u
              hq.heappush(pqueue, (f, v))
            
  return path, cost

In [89]:
def route(path, e, sp):
  if path[e] != -1:
    route(path, path[e], sp)
  sp.append(e) 
  return sp

In [90]:
def path_visualization(path, end):
  n = len(path)
  new_path = [-1]*n
  while path[end] > -1:
    new_path[end] = path[end]
    end = path[end]
  return new_path

In [91]:
def function_path(G, first, end, p):
  sp = []
  path, cost = dijkstra(G, first, end, p)
  p = cost[end]
  if p == math.inf:
    return
  else:
    print(f"Ruta: {route(path, end, sp)}")
    print(f"Costo: {cost[end]}")
    n_path = path_visualization(path, end)
    return n_path, p

In [92]:
while True:
  print("1. Ingresar datos para rutas mas cortas")
  print("2. Salir")
  op = int(input("Ingrese opcion: "))
  if (op == 1):
    op1= int(input("\nIngrese n° nodo actual: "))
    op2= int(input("Ingrese n° nodo destino: "))
    if (op1 >= 0 and op1 <= 1728) and (op2 >= 0 and op2 <= 1728):
      p = 0
      print("\nResultados: ")
      for _ in range(3):
        print()
        n_path, p = function_path(a, op1, op2, p)
        adjlShow(a, weighted=True, path=n_path, layout="neato")
      print()
    else:
      break
  else:
    break

1. Ingresar datos para rutas mas cortas
2. Salir
Ingrese opcion: 1

Ingrese n° nodo actual: 34
Ingrese n° nodo destino: 1200

Resultados: 

Ruta: [34, 73, 117, 161, 205, 249, 291, 334, 377, 420, 463, 505, 548, 592, 636, 680, 722, 763, 806, 849, 848, 883, 882, 918, 952, 951, 950, 989, 1029, 1028, 1071, 1114, 1157, 1200]
Costo: 3.766916631339937

Ruta: [34, 73, 117, 161, 205, 249, 291, 334, 377, 420, 463, 505, 548, 592, 636, 680, 722, 763, 806, 849, 848, 883, 882, 918, 952, 951, 950, 989, 1029, 1072, 1115, 1158, 1201, 1200]
Costo: 3.77041697886459

Ruta: [34, 73, 117, 161, 205, 249, 291, 334, 377, 420, 463, 505, 548, 592, 636, 680, 722, 763, 806, 849, 848, 883, 882, 918, 952, 951, 950, 989, 1029, 1028, 1071, 1070, 1113, 1156, 1199, 1200]
Costo: 3.9058833668009774

1. Ingresar datos para rutas mas cortas
2. Salir
Ingrese opcion: 2
